### PR TITLE
replace collections with eclipse collections

### PR DESCRIPTION
**Pull request by p1tz**
this replaces 
* a lot of classes where there should have been interfaces
* list and map with https://www.eclipse.org/collections/ (reduced memory footprint)

if you don't like it, please close :)

(we deal with a lot of apis that have unknown json parameters, so all mapping to classes is not useful to us)

### CODE REVIEW

**Comment by zapov** [comment]
Tnx. Faster collections is something worth looking into... but I would also like to see some benchmarks.
I don't mind changing all those ArrayLists into Lists... that shouldn't be a problem on most of the places...
But ideally there should not be additional dependencies, meaning different collections should be somewhat configurable (eg, collection factory on few places)

Can you provide few benchmarks alongside this PR?

**Comment by zapov** [comment]
So I looked at this briefly... and put branch on: https://github.com/ngs-doo/dsl-json/tree/custom-collections

But it's noticeable slower on the bench I used (https://github.com/cowtowncoder/java-json-performance-benchmarks)
I've added:

    static class EclipseJson extends DslJson<Object> {
        @Override
        public JsonReader<Object> newReader(byte[] bytes, int length) {
            return new DZoneReadMapDslJson.EclipseReader(bytes, length, new char[64], keyCache);
        }
        @Override
        public JsonStreamReader<Object> newReader(InputStream stream, byte[] buffer) throws IOException {
            return new EclipseStreamReader(stream, buffer, keyCache);
        }

    }
    static final class EclipseStreamReader extends JsonStreamReader<Object> {
        public EclipseStreamReader(final InputStream stream, final byte[] buffer, KeyCache keyCache) throws IOException {
            super(stream, buffer, null, keyCache);
        }
        @Override
        public <T> List<T> emptyList() {
            return FastList.newList(0);
        }
        @Override
        public <T> List<T> newList() {
            return FastList.newList(4);
        }
        @Override
        public <T> Map<String, T> emptyMap() {
            return UnifiedMap.newMap(0);
        }
        @Override
        public <T> Map<String, T> newMap() {
            return UnifiedMap.newMap(4);
        }
    }
    static final class EclipseReader extends JsonReader<Object> {
        public EclipseReader(byte[] bytes, int len, char[] tmp, KeyCache cache) {
            super(tmp, bytes, len, null, cache);
        }
        @Override
        public <T> List<T> emptyList() {
            return FastList.newList(0);
        }
        @Override
        public <T> List<T> newList() {
            return FastList.newList(4);
        }
        @Override
        public <T> Map<String, T> emptyMap() {
            return UnifiedMap.newMap(0);
        }
        @Override
        public <T> Map<String, T> newMap() {
            return UnifiedMap.newMap(4);
        }
    }
    private final DslJson<Object> dsl;
    private final byte[] buffer = new byte[8192];

    public DZoneReadPojoDslJson()
    {
        dsl = new EclipseJson();
    }

in read tests and it's about 10-20% slower with vanilla DSL-JSON... and around 10% slower with Eclipse collections.

**Comment by p1tz** [comment]
thank you :)

I get that, I will do the benchmark, and look at the rest.

anyway, with unstructured json I see more gain from reduced memory footprint. but again, thats me :)

**Comment by zapov** [comment]
I did add one important feature for that use case in 1.3
Now it has a key cache, which helps both with memory usage and performance.

**Comment by zapov** [comment]
Is there any point in pursuing this or string cache helped?

**Pull request closed without merging**
