### PR TITLE
[Feature] @JsonEnumDefaultValue annotation

### PR DESCRIPTION
**Pull request by amakaroff**
Hello!
My project used the @JsonEnumDefaultValue and I want to migrate [dsl-json](https://github.com/ngs-doo/dsl-json).
So that annotation is really necessary for me.
I think it can be usful for dsl-json

### CODE REVIEW

**Comment by zapov** [comment]
You should be able to get such behavior by declaring JsonConverter for those enums. Did you try that?
While it might not be the same as declaring enum on a label, it is relatively simple and allows for greater control.

**Comment by zapov** [comment]
And if you want to take it a step further, you can actually implement annotation processor to handle this Jackson annotation and generate this JsonConverters of DSL-JSON.
This way you should be able to fully replicate Jackson behavior, while not really doing any change in DSL-JSON.

**Comment by amakaroff** [comment]
Yea, but at now I need to create an own JsonConverter for each enum in my project, so it's not useful, when you have many enums in project. So it's not  useful for migrating from Jackson to Dsl-Json.
Did you mean, I can create my own AnnotationProcessor for parsing JsonEnumDefaultValue annotation to JsonConverter? But I think I still need to create JsonConverter for all enums in my project. 
I'm not sure, can I to create single Converter for all enums for processing JsonEnumDefaultValue?

**Comment by zapov** [comment]
Yes, I meant that you create your own AnnotationProcessor for parsing JsonEnumDefaultValue and creating expected code.
I suggest you first do it manually for one enum. And then just have processor create it for all others tagged with annotation.
DSL-JSON is creating converters for each enum anyway... so its not like you will have much more generated code anyway.

**Comment by amakaroff** [comment]
Okay, I'll try it, thanks for your help
I created that PR, as I thought these changes can be useful for dsl-json, so let it's not necessary, so I'll close it

**Comment by zapov** [comment]
Do get back how it went. I think its better if you can build on top of dsl-json than have it be a kitchen sink

**Comment by amakaroff** [comment]
Sure, thank you for advice :)

**Pull request closed without merging**
